language: generic

services:
- docker

go:
- "1.11"

node_js:
- "11"

before_script:
- cd ./src/client && npm install && cd ../../

script:
- make test
- make test-client

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
